config/routes.rb
Rails.application.routes.draw do
  root                'static_pages#home'
  get    'about'   => 'static_pages#about'
  get    'contact' => 'static_pages#contact'

  get 'signup' => 'users#new', as: "signup"
  post "signup" => 'users#create' 

  resources :goals do 
    resources :savings
  end 

  resources :users

  get "login" => "sessions#new", as: "login"
  post "login" => "sessions#create" 
  get "logout" => "sessions#destroy", as: "logout"
  

end

app/models/saving.rb
# == Schema Information
#
# Table name: savings
#
#  id         :integer          not null, primary key
#  category   :string
#  amount     :decimal(5, 2)
#  goal_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Saving < ActiveRecord::Base
  validates :category, presence: true 
  validates :amount, presence: true, :format => { :with => /\A\d+(?:\.\d{0,2})?\z/ }, :numericality => {:greater_than => 0.00}
  belongs_to :goal
  belongs_to :user
end

app/controllers/savings_controller.rb
# == Schema Information
#
# Table name: savings
#
#  id         :integer          not null, primary key
#  category   :string
#  amount     :decimal(5, 2)
#  goal_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class SavingsController < ApplicationController

  def index
    @goal = Goal.find(params[:goal_id])
    @savings = @goal.savings
  end 

  def show
    goal = Goal.find(params[:goal_id])
    @saving = goal.savings.find(params[:id])
  end 

  def edit
    @goal = Goal.find(params[:goal_id])
    @saving = @goal.savings.find(params[:id])
  end 

  def new
    @goal = Goal.find(params[:goal_id])
    @saving = @goal.savings.build
  end 

  def create
    goal = Goal.find(params[:goal_id])
    @saving = goal.savings.build(saving_params)
    goal.apply_amount

    if @saving.save 
      redirect_to([@saving.goal, @saving], :notice => 'Saving applied to goal.')
    else 
      render 'new'
    end 
  end 

  def update
    @goal = Goal.find(params[:goal_id])
    @saving = @goal.savings.find(params[:id])
    @goal.apply_amount

    if @saving.update_attributes(saving_params)
      redirect_to [@saving.goal, @saving], :notice => 'Saving was successfully updated.'
    else 
      render 'edit'
    end 
  end 

  def destroy
    goal = Goal.find(params[:goal_id])
    @saving = goal.savings.find(params[:id])
    @saving.destroy
    goal.apply_amount

    redirect_to goal_savings_path(goal)
  end 

  private

  def saving_params
    params.require(:saving).permit(:category, :amount)
  end 

end

app/helpers/savings_helper.rb
# == Schema Information
#
# Table name: savings
#
#  id         :integer          not null, primary key
#  category   :string
#  amount     :decimal(5, 2)
#  goal_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

module SavingsHelper
end

app/views/savings/_form.html.erb
<%= form_for ([@goal, @saving]) do |f| %>

  <div class="saving_field">
    <%= f.label :category  %><br /> 
    <%= f.text_field :category %>
  </div>

  <div class="saving_field">
    <%= f.label :amount %><br /> 
    <%= f.text_field :amount %>
  </div>

  <div class="actions">
   <%= f.submit %> 
  </div>

<% end %>
 

app/views/savings/edit.html.erb
<html>
  <header>
    
  </header>
  <body>
    <h1>Editing saving</h1>

    <%= render "form" %>

    <%= link_to 'Show', [@saving.goal, @saving] %> |
    <%= link_to 'Back', goal_savings_path(@saving.goal) %>
  </body>
</html>

app/views/savings/index.html.erb
<h1>Listing of savings</h1>
<table>
  <tr>
    <th>Category</th>
    <th>Amount</th>
    <th>Options</th>
  </tr>

  <% @savings.each do |saving| %>
    <tr>
      <td><%= saving.category %></td>
      <td><%= saving.amount %></td>
      <td><%= link_to 'Show', [saving.goal, saving] %></td>
      <td><%= link_to 'Edit', edit_goal_saving_path(saving.goal, saving) %></td>
      <td><%= link_to 'Destroy', [saving.goal, saving], :confirm => "Are you sure?", :method => :delete %></td>
    </tr>
  <% end %>
</table>

<br /> 

<%= link_to 'New Saving', new_goal_saving_path %> | 
<%= link_to 'Goal', goal_path(@goal) %>

app/views/savings/new.html.erb
<h1>New saving</h1>

<%= render 'form' %>

<%= link_to 'Back', goal_savings_path(@saving.goal) %>

app/views/savings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Category:</strong><br>
  <%= @saving.category %>
</p>

<p>
  <strong>Amount:</strong><br>
  <%= @saving.amount %>
</p>

<%= link_to 'Edit', edit_goal_saving_path(@saving.goal, @saving) %> |
<%= link_to 'Back', goal_savings_path(@saving.goal) %>