config/routes.rb
Rails.application.routes.draw do
  root                'static_pages#home'
  get    'about'   => 'static_pages#about'
  get    'contact' => 'static_pages#contact'

  get 'signup' => 'users#new', as: "signup"
  post "signup" => 'users#create' 

  resources :goals do 
    resources :savings
  end 

  resources :users

  get "login" => "sessions#new", as: "login"
  post "login" => "sessions#create" 
  get "logout" => "sessions#destroy", as: "logout"
  

end

app/models/goal.rb
# == Schema Information
#
# Table name: goals
#
#  id            :integer          not null, primary key
#  name          :string
#  goal_amount   :decimal(10, 2)
#  saved_amount  :decimal(10, 2)   default(0.0)
#  goal_progress :integer          default(0)
#  goal_met      :boolean          default(FALSE)
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  user_id       :integer
#

class Goal < ActiveRecord::Base
  has_many :savings
  belongs_to :user

  validates :goal_amount, presence: true, :format => { :with => /\A\d+(?:\.\d{0,2})?\z/ }, :numericality => {:greater_than => 0}
  validates :name, presence: true, :length => { :in => 2..20 }
  accepts_nested_attributes_for :savings

  def apply_amount
    update_goal_amount
    update_saved_amount
    self.save
  end 

  def update_goal_amount
    self.savings.each do |saving| 
      self.goal_amount -= saving.amount
    end 
  end 

  def update_saved_amount
    self.savings.each do |saving| 
      self.saved_amount += saving.amount
    end 
  end 

end

app/controllers/goals_controller.rb
# == Schema Information
#
# Table name: goals
#
#  id            :integer          not null, primary key
#  name          :string
#  goal_amount   :decimal(10, 2)
#  saved_amount  :decimal(10, 2)   default(0.0)
#  goal_progress :integer          default(0)
#  goal_met      :boolean          default(FALSE)
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  user_id       :integer
#

class GoalsController < ApplicationController
  before_filter :current_user

  def current_user
    @current_user = @current_user || User.find_by(id: session[:user_id])
  end 

  def index
    @goals = Goal.all
  end 

  def new
    @goal = Goal.new
    @saving = @goal.savings.build
  end 

  def show
    @goal = Goal.find(params[:id])
  end 

  def create
    @goal = Goal.new(goal_params)
    if @goal.valid? 
      @goal.save
      redirect_to goal_path(@goal)
    else 
      render 'new'
    end 
  end 

  def edit
    @goal = Goal.find(params[:id])
    @goal.savings.build
  end 

  def update
    @goal = Goal.find(params[:id])
    @goal.update(goal_params)
    if @goal.valid?
      @goal.update(goal_params)
      redirect_to goal_path(@goal)
    else 
      render 'edit'
    end 
  end 

  private

  def goal_params
    params.require(:goal).permit(:name, :goal_amount, :saving_attributes => [:category, :amount])
  end

end

app/helpers/goals_helper.rb
# == Schema Information
#
# Table name: goals
#
#  id            :integer          not null, primary key
#  name          :string
#  goal_amount   :decimal(10, 2)
#  saved_amount  :decimal(10, 2)   default(0.0)
#  goal_progress :integer          default(0)
#  goal_met      :boolean          default(FALSE)
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  user_id       :integer
#

module GoalsHelper
end

app/views/goals/_form.html.erb
<%= form_for @goal do |f| %>

  <% if @goal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@goal.errors.count, "error") %> prohibited this from being saved: </h2>
      <ul>
        <% @goal.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<p>
<%= f.label :name %><br>
<%= f.text_field :name %>
</p>

<p>
<%= f.label :goal_amount %><br>
<%= f.text_field :goal_amount %>
</p>

<% if @goal.persisted? %>
  <p>
    <%= render "savings/form" %>
  </p>
<% end %>

<%= f.submit %>
<% end %>

app/views/goals/edit.html.erb
<html>
<header>
  
</header>
<body>

<%= render "form" %>


</body>
</html>

app/views/goals/index.html.erb
<% @goals.each do |goal| %>
<%= link_to goal.name, goal_path(goal) %>
<% end %>

app/views/goals/new.html.erb
<html>
<header>
  
</header>
<body>

<%= render "form" %>

</body>
</html>

app/views/goals/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @goal.name %></h1><br>

<p>
  <strong>Goal Amount: </strong><br>
  <%= @goal.goal_amount %>
</p>

<p>
  <strong>Saved Amount:</strong><br>
  <%= @goal.saved_amount %>
</p>

<%= link_to 'Savings', goal_savings_path(@goal) %> |
<%= link_to 'Edit', edit_goal_path(@goal) %> |
<%= link_to 'Back', goals_path %>