config/routes.rb
Rails.application.routes.draw do
  root                'static_pages#home'
  get    'about'   => 'static_pages#about'
  get    'contact' => 'static_pages#contact'

  get 'signup' => 'users#new', as: "signup"
  post "signup" => 'users#create' 

  resources :goals do 
    resources :savings
  end 

  resources :users

  get "login" => "sessions#new", as: "login"
  post "login" => "sessions#create" 
  get "logout" => "sessions#destroy", as: "logout"
  

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    &copy; Brown Bag -- Build Willpower</a>
    by Jeffrey Wang</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "BrownBag", goals_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>

        <% if logged_in? %>
          <li><%= link_to "Goals", goals_path %></li>
          <li><%= link_to "Savings", new_goal_path %></li>
          
          <li class="dropdown"> 
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"> 
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown_menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", "#" %></li>
              <li class="divider"></li>
              <li><%= link_to "Log out", logout_path, method: "delete" %></li>
            </ul>
          </li>

        <% else %>
          <li><%= link_to "Log in", login_path %></li>
          <li class="divider"></li>
          <li><%= link_to "Sign up", signup_path %></li>
        <% end %>

      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BrownBag</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render "layouts/header" %>

  <div class="container">
    <%= yield %> 
  </div>

  <%= render "layouts/footer" %>

</body>
</html>